# Site
title:              Ryan's Blog
bio:                "Ryan's blog for Databases and Web Systems"
description:        "Ryan's blog for Databases and Web Systems"
locale:             en_US
baseurl: /blog
url: http://ryfuller03.github.io

plugins_dir:
  - jekyll-feed
  - jekyll-seo-tag

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          default
github:             https://github.com/ryfuller03

# personal
email:              fullerra@hendrix.edu # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:title/"
    layout: post
    author:

# Jekyll
permalink:          "/:title/"
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/page:num/"

jekyll-mentions:
    base_url: https://github.com

minima:
  - { platform: github, user_url: "https://github.com/ryfuller03"}

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
